### ISSUE TITLE
Trying to check if a coin exists in the collection already

### ISSUE THREAD

**Issue by RufusIbiza** [RufusIbiza/binance#1]
keep getting a "[ 'Parse error: Can\'t wait without a fiber' ]'. error when trying to do a collection.findOne call in main.js in the _each loop. 
Can anyone help?

**Comment by nikdale** [comment]
Everything fixed in the [this commit](https://github.com/RufusIbiza/binance/commit/4285585e987b9e0615a3bf59075761986e033ddf)
